[supervisord]
nodaemon=true
user=root

[program:threat-api]
directory=/app/dns-threat-filter/api
command=uvicorn main:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:threat-dashboard]
directory=/app/dns-threat-filter/dashboard
command=streamlit run app.py --server.port 8502 --server.address 0.0.0.0
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:coredns]
directory=/app/dns-threat-filter/coredns-plugin
command=./coredns -conf Corefile.dev
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:military-app]
directory=/app/military-intel-platform
command=streamlit run app.py --server.port 8501 --server.address 0.0.0.0
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
